### ISSUE TITLE
Can this be adapted to proxy multiple HTTP and websocket backends?

### ISSUE THREAD

**Issue by stodge** [thinxer/tornado-proxy-server#6]
Can this be adapted to proxy multiple HTTP and websocket backends? Thanks

**Comment by thinxer** [comment]
It supports multiple backends by using the "rules" connector. There is an example in the README.md. You can dispatch different URL patterns to different servers.

Currently it has no support for WebSocket. I'm not actively using this software recently and I'm sorry for not being able to support WebSocket.
